# DB Parameters
rds_database:
database_name: "AuroraDB"
database_backup_retention_period: 1
engine: "aurora-mysql"
database_engine_family: "aurora-mysql5.7"
engine_version: "5.7.mysql_aurora.2.10.2"
storage_encryption: True
db_instance_type: "db.t3.large"
# database_deletion_protection: False
database_instance_storage_type: "gp2"
master_username: "root"
database_instances_count: 2
database_default_port: 3306
cpu_usage_high_alarm_evaluation_periods: 5
cpu_usage_high_alarm_period: 60
cpu_usage_high_alarm_threshold: 60
database_free_storage_evaluation_periods: 5
database_free_storage_space_alarm_threshold: 50000000
database_free_storage_space_alarm_period: 60